# -*- coding: utf-8 -*-
"""analise-exploratoria-de-dados-aula3-18ago2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UG6XkshlDZaTy6RFchuBKRrPP2NT88v3
"""

import pandas as pd

dados = pd.read_csv('gapminder_data.csv')

dados

dados.info()

dados.describe()

dados.query('country == "Brazil" and year == 1977')

dados.groupby(['year', 'continent']).agg({'lifeExp':['mean', 'max'], 'gdpPercap':'median'})

brasil = dados.query('country == "Brazil"')

brasil.plot('year', 'gdpPercap')

dados.head()

dados.rename(columns={'lifeExp':'expec_vida'})

## graficos com a biblioteca altair

import altair as alt

alt.Chart(dados).mark_point().encode(
    x = 'year:O',
    y = 'lifeExp'
).interactive()

alt.Chart(dados.query('year == 2007 and country != "Brazil"')).mark_point(filled=True, size=70).encode(
    x = 'gdpPercap',
    y = 'lifeExp',
    color = 'continent',
    size = 'pop',
    tooltip = ['country', 'continent', 'gdpPercap', 'lifeExp']
).properties(
    title = 'Africa ainda vive menos'
).interactive()

alt.Chart(dados.query('year == 2007 and country == "Brazil"')).mark_point(filled=True, size=70).encode(
    x = 'gdpPercap',
    y = 'lifeExp',
    color = 'continent',
    size = 'pop',
    tooltip = ['country', 'continent', 'gdpPercap', 'lifeExp']
).properties(
    title = 'Africa ainda vive menos'
).interactive()

# se quisermos diferenciar o brasil no grafico podemos criar um grafico igual
# com filtro para o brasil e depois usar o + para sobrepor com o grafico do mundo

